### ISSUE TITLE
Validation error when specifying "file" as response type

### ISSUE THREAD

**Issue by sharpworks** [gersongoulart/gulp-swagger#4]
Hi,

When trying to validate a definition which returns file as a response type I get the following error:

>  Data does not match any schemas from 'oneOf'

An example of the spec which produces the error is:

``` yaml
responses:
    '200':
         description: OK
         schema:
             type: file
```

The file validates fine when viewed/edited in the [swagger editor](http://editor.swagger.io) however fails when run through the gulp task.

It appears to be the same issue in the spec [found here](https://github.com/OAI/OpenAPI-Specification/issues/260).

Thanks

**Comment by gersongoulart** [comment]
Hey @sharpworks, it seems like there was a problem in one of the validation packages used. I just updated all dependencies to the project and I believe this should be working properly now. Would you please update and let me know if it works for you? Cheers!
