### ISSUE TITLE
Validate only?

### ISSUE THREAD

**Issue by cviebrock** [gersongoulart/gulp-swagger#8]
Is it possible to use your package for validation only?  So I could do something like:

``` js
gulp.src('./build/swagger.json')
    .pipe(swagger({
        validateOnly: true
    }))
    .pipe(prettify({
        config: '.jsbeautifyrc',
        mode: 'VERIFY_AND_WRITE'
    }))
    .pipe(gulp.dest('./public'));
```

The reason being that I have a (non-gulp) tool generating my JSON but it doesn't do a good validation test.  I don't need anything dereferenced ... just validated. :)

**Comment by gersongoulart** [comment]
Hi @cviebrock, this should now be possible as of v1.0.1:

``` javascript
gulp.src('./build/swagger.json')
    .pipe(swagger())
    .pipe(prettify({
        config: '.jsbeautifyrc',
        mode: 'VERIFY_AND_WRITE'
    }))
    .pipe(gulp.dest('./public'));
```

Please let me know if it works as intend for you.

**Comment by cviebrock** [comment]
Thanks @gersongoulart!  I'll give this a try ... although `npm install` is saying there isn't a 1.0.1 version yet.

**Comment by gersongoulart** [comment]
You bet... I made a mistake and the version was never published. This is resolved now.
